- name: Install Docker on all private_ec2 and run latest image.
  hosts: proxy
  become: true
  tasks:
    - name: Run Yum Update
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Install Docker
      command: amazon-linux-extras install docker -y
      register: my_command_output

    - name: Print the output of the 'Install Docker' command
      debug:
        var: my_command_output.stdout_lines

    - name: Start Docker Service
      command: service docker start
      register: my_command_output

    - name: Print the output of the 'Start Docker Service' command
      debug:
        var: my_command_output.stdout_lines

    - name: Pull Latest Docker Image     
      command: docker pull public.ecr.aws/g4x4w1s3/monty-hall-game:e164f5485f753e77c8f919161c6d9f157e43646f

    - name: Run Docker container 
      command: docker run -d --name ECR-Container -p 80:5000 public.ecr.aws/g4x4w1s3/monty-hall-game:e164f5485f753e77c8f919161c6d9f157e43646f
